### ISSUE TITLE
Love Frames: text input issue

### ISSUE THREAD

**Issue by easy82** [binji/love-nacl#18] opened 2013-05-02 09:50 UTC
Löveliness doesn't seem to handle well text input fields, see example here:
http://archive.nikolairesokav.com/love/loveframes/loveframes-demo.love

Scroll down in the example list and select text input, then try to write some text in the window appearing. The cursor is blinking, but no text can be written. I've seen this in another text input example, see the links here:
https://love2d.org/forums/viewtopic.php?f=5&t=23304

**Comment by binji** [comment] 2013-05-02 16:07
Duplicate of issue #4.

**Closed as completed by binji** 2013-05-02 16:07 UTC
Labels: duplicate

**Comment by marcocult** [comment] 2014-05-13 14:49
This seem to be still happening. Textinput doesn't show anything when I type in it.
